# Generated by Django 5.2 on 2026-07-09 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_tutores_y_expiracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='presencial',
        ),
        migrations.AlterField(
            model_name='tutor',
            name='foto_url',
            field=models.URLField(blank=True, help_text='URL externa de la foto (alternativa a ImageField)'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='requisitos',
            field=models.TextField(blank=True, help_text='Que debe saber el alumno antes de esta tutoria'),
        ),
        migrations.CreateModel(
            name='ServicioTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presencial', models.BooleanField(default=False, help_text='Si es True, esta modalidad de este tutor requiere Plan Premium.')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicio_tutores', to='citas.servicio')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_servicios', to='citas.tutor')),
            ],
            options={
                'unique_together': {('servicio', 'tutor')},
            },
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tutores',
        ),
        migrations.AddField(
            model_name='servicio',
            name='tutores',
            field=models.ManyToManyField(blank=True, related_name='servicios', through='citas.ServicioTutor', to='citas.tutor'),
        ),
    ]
