# Generated by Django 5.2 on 2026-07-10 02:16

import citas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_remove_servicio_presencial_alter_tutor_foto_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='ocupado',
        ),
        migrations.AddField(
            model_name='cita',
            name='direccion_alumno',
            field=models.CharField(blank=True, help_text='Dirección/zona que el alumno indicó para la tutoría presencial.', max_length=255),
        ),
        migrations.AddField(
            model_name='cita',
            name='meet_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='meet_password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=1, help_text='Cupo máximo de alumnos. Virtual: hasta 15. Presencial (premium): debe ser 1 (individual).'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número de WhatsApp con código de país, ej: 51987654321 (sin espacios ni +)', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='disponibilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='citas.disponibilidad'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='expira_en',
            field=models.DateTimeField(default=citas.models._expiracion_default, help_text='Si sigue pendiente después de este momento, se cancela automáticamente.'),
        ),
    ]
